#Docker compose yml
version: '3.3'
services:
  wizer_lib_api:
    container_name: wizer-lib-api
    image: wizer-lib
    build: ./
    ports:
      - "8000:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=wizer
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wizer_lib
