spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false


server:
  port: ${PORT:5001}
  servlet:
    context-path: /
api:
  url-domain: http://localhost:5001${server.servlet.context-path}


