#spring.datasource.url=jdbc:postgresql://postgresqldb:5432/wizer_lib
#spring.datasource.url: jdbc:postgresql://localhost:5432/wizer_lib
#spring.datasource.username: postgres
#spring.datasource.password: wizer
#
#spring.jpa.hibernate.ddl-auto: update
#spring.jpa.show-sql: false
#spring.datasource.driver-class-name: org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql: true

#api:
#  url-domain: http://localhost:8080
#  basepath-api: /api

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${RDS_HOSTNAME:postgresqldb}:${RDS_PORT:5432}/${RDS_DB_NAME:wizer_lib}}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:wizer}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false


server:
  port: ${PORT:5001}
  servlet:
    context-path: /${CONTEXT_PATH:}
---
api:
  url-domain: ${APP_URL_DOMAIN:http://localhost:${server.port}${server.servlet.context-path}}
  basepath: /api/v1
