#spring.datasource.url=jdbc:postgresql://postgresqldb:5432/wizer_lib
spring.datasource.url: jdbc:postgresql://localhost:5432/wizer_lib
spring.datasource.username: postgres
spring.datasource.password: wizer

spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql: true

api:
  url-domain: http://localhost:8080
  basepath-api: /api
